const allProducts = [
	{
		id: 1,
		name: "Product_1",
		description: "A versatile gadget for everyday use. Durable and efficient.",
		price: 10,
		isInStock: true,
		image: "../assets/products/1.png",
	},
	{
		id: 2,
		name: "Product_2",
		description: "High-quality item designed for long-lasting performance.",
		price: 25,
		isInStock: false,
		image: "../assets/products/2.png",
	},
	{
		id: 3,
		name: "Product_3",
		description: "Compact and powerful, perfect for on-the-go needs.",
		price: 50,
		isInStock: true,
		image: "../assets/products/3.png",
	},
	{
		id: 4,
		name: "Product_4",
		description: "An essential tool for professionals and hobbyists alike.",
		price: 75,
		isInStock: true,
		image: "../assets/products/4.png",
	},
	{
		id: 5,
		name: "Product_5",
		description:
			"Innovative design meets incredible functionality. A must-have!",
		price: 120,
		isInStock: false,
		image: "../assets/products/5.png",
	},
	{
		id: 6,
		name: "Product_6",
		description:
			"Affordable and reliable, offering great value for your money.",
		price: 30,
		isInStock: true,
		image: "../assets/products/6.png",
	},
	{
		id: 7,
		name: "Product_7",
		description: "Premium quality with a sleek finish, enhancing any setup.",
		price: 90,
		isInStock: true,
		image: "../assets/products/7.png",
	},
	{
		id: 8,
		name: "Product_8",
		description: "Simple to use, yet incredibly effective for daily tasks.",
		price: 45,
		isInStock: true,
		image: "../assets/products/8.png",
	},
	{
		id: 9,
		name: "Product_9",
		description: "A robust solution built to withstand rigorous conditions.",
		price: 150,
		isInStock: false,
		image: "../assets/products/9.png",
	},
	{
		id: 10,
		name: "Product_10",
		description: "Ergonomic design for maximum comfort and efficiency.",
		price: 65,
		isInStock: true,
		image: "../assets/products/10.png",
	},
];
