export const allProducts = [
	{
		id: 1,
		name: "The Versatile Gadget Pro",
		description: "A versatile gadget for everyday use. Durable and efficient.",
		price: 10,
		isInStock: true,
		image: "/products/1.png",
	},
	{
		id: 2,
		name: "Everlast Performance Tool",
		description: "High-quality item designed for long-lasting performance.",
		price: 25,
		isInStock: false,
		image: "/products/2.png",
	},
	{
		id: 3,
		name: "The On-The-Go Power Hub",
		description: "Compact and powerful, perfect for on-the-go needs.",
		price: 50,
		isInStock: true,
		image: "/products/3.png",
	},
	{
		id: 4,
		name: "The Professional's Essential",
		description: "An essential tool for professionals and hobbyists alike.",
		price: 75,
		isInStock: true,
		image: "/products/4.png",
	},
	{
		id: 5,
		name: "The Innovator's Delight",
		description:
			"Innovative design meets incredible functionality. A must-have!",
		price: 120,
		isInStock: false,
		image: "/products/5.png",
	},
	{
		id: 6,
		name: "The Smart Value Companion",
		description:
			"Affordable and reliable, offering great value for your money.",
		price: 30,
		isInStock: true,
		image: "/products/6.png",
	},
	{
		id: 7,
		name: "The Sleek Elite Display",
		description: "Premium quality with a sleek finish, enhancing any setup.",
		price: 90,
		isInStock: true,
		image: "/products/7.png",
	},
	{
		id: 8,
		name: "The Effortless Everyday Helper",
		description: "Simple to use, yet incredibly effective for daily tasks.",
		price: 45,
		isInStock: true,
		image: "/products/8.png",
	},
	{
		id: 9,
		name: "The Rugged Durability Master",
		description: "A robust solution built to withstand rigorous conditions.",
		price: 150,
		isInStock: false,
		image: "/products/9.png",
	},
	{
		id: 10,
		name: "The Comfort Ergonomic Solution",
		description: "Ergonomic design for maximum comfort and efficiency.",
		price: 65,
		isInStock: true,
		image: "/products/10.png",
	},
	{
		id: 11,
		name: "The Guardian Smart Lock",
		description: "Advanced security for your home, controlled with ease.",
		price: 180,
		isInStock: true,
		image: "/products/11.png",
	},
	{
		id: 12,
		name: "The Culinary Master Blender",
		description: "Unleash your inner chef with powerful blending capabilities.",
		price: 110,
		isInStock: true,
		image: "/products/12.png",
	},
];
